# 站点信息
SITE_TITLE: 'SPlayer'
SITE_ANTHOR: 'Hlhs'
SITE_KEYWORDS: 'SPlayer,云音乐,播放器,在线音乐,在线播放器,音乐播放器'
SITE_DES: '一个简约的在线音乐播放器，具有音乐搜索、播放、每日推荐、私人FM、歌词显示、歌曲评论、网易云登录与云盘等功能'
SITE_URL: 'example.com'

# API 地址（ 结尾不要加 / ）
SERVER_URL: './api'

# 公告配置 (若无需公告，请将标题或内容任意一项设为空即可)
## 公告类型 info、success、warning、error
ANN_TYPE: 'info'
## 公告标题
ANN_TITLE: ''
## 公告内容
ANN_CONTENT: ''
## 公告时长（毫秒）不可超过 999999
ANN_DURATION: 8000
