# 启动端口，请确保端口未被占用
Port: 3000

# 是否使用https，需要在data/SSL目录存放并命名certificate.crt private.key两个证书文件
Https: false

# 您对外显示的域名或IP地址
Host: 127.0.0.1

# 为/register添加?key=114514校验，留空则不校验
Key: '114514'

# HTML页脚标签内容
Copyright: 'Copyright Miao-Yunzai'